# Generated by Django 4.2 on 2024-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', help_text='Indica si el usuario está activo o inactivo.', max_length=8),
        ),
    ]
