# Generated by Django 4.2 on 2024-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correoElectronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
