# Generated by Django 4.2 on 2025-01-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('instructor', 'curso', 'activo')},
        ),
    ]
