# Generated by Django 4.2 on 2024-12-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0002_alter_empresa_correoelectronico_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='codigoOrganizacion',
            field=models.CharField(max_length=100),
        ),
    ]
