# Generated by Django 4.2 on 2024-12-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0003_alter_instructor_codigoorganizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='descripcion',
        ),
    ]
