# Generated by Django 4.2 on 2024-08-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0003_alter_administrador_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
