# Generated by Django 4.2 on 2024-12-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0004_remove_modulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='debeCambiarContraseña',
            field=models.BooleanField(default=True),
        ),
    ]
