# Generated by Django 4.2 on 2024-08-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0004_alter_administrador_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
    ]
