# Generated by Django 4.2 on 2024-12-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0005_instructor_debecambiarcontraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='fechaFinCurso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='fechaInicioCurso',
            field=models.DateField(null=True),
        ),
    ]
