# Generated by Django 4.2 on 2024-12-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0005_instructor_debecambiarcontraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estaAprobado', models.BooleanField(default=False)),
                ('calificacion', models.FloatField(default=0.0)),
                ('intento', models.IntegerField(default=0)),
                ('fechaPrueba', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='fechaEvaluacion',
            new_name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='asignadoSimulacion',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='estaAprobado',
        ),
        migrations.RemoveField(
            model_name='subcurso',
            name='progreso',
        ),
        migrations.AddField(
            model_name='curso',
            name='simulacion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='contenidoCompletado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='fechaFinCurso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='fechaInicioCurso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='simulacionCompletada',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Simulacion',
        ),
        migrations.AddField(
            model_name='estudianteprueba',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_prueba', to='globalqhse.estudiante'),
        ),
        migrations.AddField(
            model_name='estudianteprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='globalqhse.prueba'),
        ),
        migrations.AlterUniqueTogether(
            name='estudianteprueba',
            unique_together={('estudiante', 'prueba')},
        ),
    ]
