# Generated by Django 4.2 on 2024-08-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0005_remove_usuario_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
    ]
