# Generated by Django 4.2 on 2024-12-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0006_progreso_fechafincurso_progreso_fechainiciocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='fechaInicioCurso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
