# Generated by Django 4.2 on 2024-12-26 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0007_alter_progreso_fechainiciocurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={},
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivoPdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='globalqhse.estudiante'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='globalqhse.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('estudiante', 'curso')},
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='codigoCertificado',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='estado',
        ),
    ]
