# Generated by Django 4.2 on 2024-09-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0007_simulacion_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidadModulos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('estaAprobado', models.BooleanField(default=False)),
                ('calificacion', models.FloatField()),
                ('fechaEvaluacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Prueba',
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='simulacion',
            options={'verbose_name': 'Simulación', 'verbose_name_plural': 'Simulaciones'},
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('porcentajeCompletado', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalqhse.cliente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalqhse.curso')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progreso',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('opcionesRespuestas', models.TextField()),
                ('respuestaCorrecta', models.CharField(max_length=255)),
                ('puntajePregunta', models.IntegerField()),
                ('tema', models.CharField(max_length=100)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='globalqhse.prueba')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion', models.IntegerField(help_text='Duración del módulo en minutos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='globalqhse.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='modulos_contenidos/')),
                ('enlace', models.URLField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='globalqhse.modulo')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenido',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCertificado', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('fechaEmision', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='globalqhse.curso')),
                ('simulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='globalqhse.simulacion')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='CursoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalqhse.curso')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalqhse.prueba')),
            ],
            options={
                'verbose_name': 'CursoPrueba',
                'verbose_name_plural': 'CursoPrueba',
                'unique_together': {('curso', 'prueba')},
            },
        ),
    ]
