# Generated by Django 4.2 on 2024-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0008_alter_certificado_options_certificado_archivopdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='asignadoSimulacion',
        ),
        migrations.AddField(
            model_name='curso',
            name='simulacion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='simulacionCompletada',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Simulacion',
        ),
    ]
