# Generated by Django 4.2 on 2024-09-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0008_curso_prueba_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='simulacion',
            name='clientes',
            field=models.ManyToManyField(related_name='simulaciones_asignadas', to='globalqhse.cliente'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='instructor_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones_asignadas', to='globalqhse.instructor'),
        ),
    ]
