# Generated by Django 4.2 on 2024-12-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0009_remove_estudiante_asignadosimulacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='fechaEvaluacion',
            new_name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='estaAprobado',
        ),
        migrations.RemoveField(
            model_name='subcurso',
            name='progreso',
        ),
        migrations.CreateModel(
            name='EstudiantePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estaAprobado', models.BooleanField(default=False)),
                ('calificacion', models.FloatField(default=0.0)),
                ('intento', models.IntegerField(default=0)),
                ('fechaPrueba', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_prueba', to='globalqhse.estudiante')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='globalqhse.prueba')),
            ],
            options={
                'unique_together': {('estudiante', 'prueba')},
            },
        ),
    ]
