# Generated by Django 4.2 on 2024-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0009_alter_usuario_options_remove_simulacion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='simulaciones_asignadas', to='globalqhse.cliente'),
        ),
    ]
