# Generated by Django 4.2 on 2024-09-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0010_alter_simulacion_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacion',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='instructor_responsable',
        ),
        migrations.AddField(
            model_name='simulacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='globalqhse.cliente'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
