# Generated by Django 4.2 on 2024-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0010_rename_fechaevaluacion_prueba_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='contenidoCompletado',
            field=models.BooleanField(null=True),
        ),
    ]
