# Generated by Django 4.2 on 2024-09-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0011_remove_simulacion_clientes_remove_simulacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulacion', to='globalqhse.cliente'),
        ),
    ]
