# Generated by Django 4.2 on 2025-01-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0011_progreso_contenidocompletado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteSubcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('porcentajeCompletado', models.FloatField(default=0.0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcursos', to='globalqhse.estudiante')),
                ('subcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='globalqhse.subcurso')),
            ],
            options={
                'verbose_name': 'Estudiante-Subcurso',
                'verbose_name_plural': 'Estudiantes-Subcursos',
                'unique_together': {('estudiante', 'subcurso')},
            },
        ),
        migrations.CreateModel(
            name='EstudianteModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='globalqhse.estudiante')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='globalqhse.modulo')),
            ],
            options={
                'verbose_name': 'Estudiante-Modulo',
                'verbose_name_plural': 'Estudiantes-Modulos',
                'unique_together': {('estudiante', 'modulo')},
            },
        ),
    ]
