# Generated by Django 4.2 on 2025-01-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0012_estudiantesubcurso_estudiantemodulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoOrganizacion', models.CharField(max_length=100)),
                ('fechaInicioCapacitacion', models.DateField()),
                ('fechaFinCapacitacion', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructores_asignados', to='globalqhse.curso')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='codigoOrganizacion',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='fechaFinCapacitacion',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='fechaInicioCapacitacion',
        ),
        migrations.DeleteModel(
            name='InstructorCurso',
        ),
        migrations.AddField(
            model_name='contrato',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='globalqhse.instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('instructor', 'curso')},
        ),
    ]
