# Generated by Django 4.2 on 2024-09-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0012_alter_simulacion_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_modulos', models.IntegerField()),
                ('progreso', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cantidadModulos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='curso',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to='globalqhse.curso'),
        ),
        migrations.DeleteModel(
            name='CursoPrueba',
        ),
        migrations.AddField(
            model_name='subcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcursos', to='globalqhse.curso'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='subcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='globalqhse.subcurso'),
        ),
    ]
