# Generated by Django 4.2 on 2025-01-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0013_contrato_remove_instructor_codigoorganizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='area',
        ),
    ]
