# Generated by Django 4.2 on 2024-09-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0013_subcurso_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='subcurso',
            options={'verbose_name': 'Subcurso', 'verbose_name_plural': 'Subcursos'},
        ),
    ]
