# Generated by Django 4.2 on 2025-01-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0014_remove_instructor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
