# Generated by Django 4.2 on 2024-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0015_modulo_completado_alter_subcurso_cantidad_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcurso',
            name='progreso',
            field=models.FloatField(default=0),
        ),
    ]
