# Generated by Django 4.2 on 2025-01-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0015_contrato_activo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('instructor', 'curso', 'activo')},
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('estudiante', 'curso')},
        ),
    ]
