# Generated by Django 4.2 on 2024-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0016_alter_subcurso_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='duracion',
        ),
        migrations.AddField(
            model_name='modulo',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace al contenido del módulo', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
