# Generated by Django 4.2 on 2024-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0017_remove_modulo_duracion_modulo_enlace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
