# Generated by Django 4.2 on 2024-09-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0018_modulo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tema',
        ),
    ]
