# Generated by Django 4.2 on 2024-10-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0019_remove_pregunta_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigoOrganizacion',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
