# Generated by Django 4.2 on 2024-10-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0020_alter_usuario_codigoorganizacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='instructor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
