# Generated by Django 4.2 on 2024-11-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0024_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigoOrganizacion',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
