# Generated by Django 4.2 on 2024-11-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0025_alter_usuario_codigoorganizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigoOrganizacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
