# Generated by Django 4.2 on 2024-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalqhse', '0026_alter_usuario_codigoorganizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='archivo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
